# Generated by Django 3.2.12 on 2022-03-14 09:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='enum_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('args_name', models.CharField(max_length=200)),
                ('project_name', models.CharField(blank=True, max_length=200, null=True)),
                ('api_name', models.CharField(blank=True, max_length=200, null=True)),
                ('api_url', models.CharField(blank=True, max_length=100, null=True)),
                ('args_value', models.CharField(blank=True, max_length=1000, null=True)),
                ('args_status', models.CharField(blank=True, max_length=10, null=True)),
                ('args_conditions', models.CharField(blank=True, max_length=200, null=True)),
                ('args_api', models.CharField(blank=True, max_length=10, null=True)),
                ('mark', models.CharField(blank=True, max_length=1000, null=True)),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='update_time')),
            ],
            options={
                'verbose_name': '参数名字',
            },
        ),
    ]
