# Generated by Django 3.2.12 on 2022-03-18 06:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myenum', '0002_crontab_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='args_sync_record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(blank=True, max_length=200, null=True)),
                ('project_id', models.CharField(blank=True, max_length=50, null=True)),
                ('api_definition', models.JSONField(blank=True, null=True)),
                ('api_md5', models.CharField(blank=True, max_length=50, null=True)),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='update_time')),
            ],
            options={
                'verbose_name': '接口定义json',
            },
        ),
    ]
